### PR TITLE
Release version 14.

### PR DESCRIPTION
**Pull request by hrqmonteiro**
Working fine on Gnome 44:
Screenshot from 2023-05-02 17-39-49

### CODE REVIEW

**Comment by binarykitchen** [comment]
Great, merge it please

**Comment by oscarcp** [comment]
For those who don't want to wait. If you modify `$HOME/.local/share/gnome-shell/extensions/weeks-start-on-monday@extensions.gnome-shell.fifi.org/metadata.json` and add "44" as one of the valid versions (line 17), it will work as well.

It's just a quick dirty patch for those who don't want to wait for the release :)

**Comment by binarykitchen** [comment]
Thanks mate

**Comment by F-i-f** [comment]
Fixed in release 14.

**Pull request closed without merging**
